/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_damn_karaoke_core_controller_processing_GoertzelToneDetectorJNI */

#ifndef _Included_com_damn_karaoke_core_controller_processing_GoertzelToneDetectorJNI
#define _Included_com_damn_karaoke_core_controller_processing_GoertzelToneDetectorJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_damn_karaoke_core_controller_processing_GoertzelToneDetectorJNI_HalftoneBase
#define com_damn_karaoke_core_controller_processing_GoertzelToneDetectorJNI_HalftoneBase 1.05946309436
#undef com_damn_karaoke_core_controller_processing_GoertzelToneDetectorJNI_BaseToneFreq
#define com_damn_karaoke_core_controller_processing_GoertzelToneDetectorJNI_BaseToneFreq 65.4064
#undef com_damn_karaoke_core_controller_processing_GoertzelToneDetectorJNI_NumHalftones
#define com_damn_karaoke_core_controller_processing_GoertzelToneDetectorJNI_NumHalftones 69L
/*
 * Class:     com_damn_karaoke_core_controller_processing_GoertzelToneDetectorJNI
 * Method:    bestMatchTone
 * Signature: ([SII)I
 */
JNIEXPORT jint JNICALL Java_com_damn_karaoke_core_controller_processing_GoertzelToneDetectorJNI_bestMatchTone
  (JNIEnv *, jclass, jshortArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
